[package]
name = "pathfinder_2e_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp-serde = "1.1.2"
serde = "1.0.192"
serde_derive = "1.0.192"
